services:
  api:
    build: .
    container_name: dex_api
    ports:
      - "3000:3000" 
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://admin:password@postgres:5432/dex_engine
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dex-network
    restart: on-failure

  # 2. Database
  postgres:
    image: postgres:15-alpine
    container_name: dex_postgres
    ports:
      - "5433:5432" # Host:5433 -> Container:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dex_engine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dex-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dex_engine"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. Queue/Cache
  redis:
    image: redis:7-alpine
    container_name: dex_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - dex-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  dex-network:
    driver: bridge

volumes:
  pgdata:
  redisdata: